classify_argus/urls.py
from django.contrib import admin
from django.urls import path, include
import polls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls')),
    path('', polls.views.login_request, name = 'login')
]

polls/urls.py
from django.urls import path
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.generic import TemplateView

app_name = 'polls'
urlpatterns = [
    path('display_image/', views.display_image, name='display_image'),
    path('vote/', views.vote, name='vote'),
    path('register/', views.register, name='register'),
    path('logout/', views.logout_request, name='logout'),
    path('login/', views.login_request, name='login'),
    path('select_site/', views.select_site, name='select_site'),
    path('site_selection/', views.site_selection, name='site_selection')
    #path('', TemplateView.as_view(template_name="site_selection.html"), name='site_selection_page')
]

urlpatterns += staticfiles_urlpatterns() #bit confused here.

polls/models.py
from __future__ import unicode_literals
from django.db import models
from django.utils.functional import cached_property
from django.contrib.auth.models import User


class Image(models.Model): #Just the actual image
    filename = models.CharField(max_length = 1000)

    def __str__(self):
        return self.filename



class State(models.Model):
    name = models.CharField(max_length = 50)

    def __str__(self): #Play with this and see how this helps
        return self.name

class User_states_image(models.Model): #Users will be creating/updating this model
    image = models.ForeignKey(Image, on_delete = models.CASCADE)
    user = models.ForeignKey(User, on_delete = models.CASCADE)
    state = models.ForeignKey(State, on_delete = models.CASCADE)




# Create your models here.

users/models.py
from django.db import models

# Create your models here.

polls/views.py
from django.shortcuts import render, get_object_or_404, redirect, render_to_response
from django.http import HttpResponse, HttpResponseRedirect
from .models import Image, State, User_states_image
from django.views import generic
from django.urls  import reverse
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib import messages
from django.contrib.auth import login, logout, authenticate


#To do :
# Create a view where the user can choose to register, or to login as a returning user.

def logout_request(request):
    logout(request)
    messages.info(request, 'Logged out successfully!')
    return redirect('polls:login')


def login_request(request):
    if request.method == 'POST':
        form = AuthenticationForm(request=request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                messages.info(request, f"You are now logged in as {username}")
                return render(request,'polls/site_selection.html')
            else:
                messages.error(request, "Invalid username or password.")
        else:
            messages.error(request, "Invalid username or password.")
    form = AuthenticationForm()

    return render(request = request,
                    template_name = "polls/login.html",
                    context={"form":form})

def register(request):

    if request.method == "POST":
        form = UserCreationForm(request.POST)

        if form.is_valid():
            form.save()
            image = Image.objects.get(pk = 3)
            username = form.cleaned_data.get('username')
            messages.success(request, f'Account Created for {username}!')
            login(request, user)
            messages.info(request, f"You are now logged in as {username}")
            return render(request,'polls/site_selection.html')
        else:
            messages.error(request, "Try registering again")
    else:
        form = UserCreationForm()

    return render(request, 'polls/register.html', {'form': form})

def display_image(request):
    user = request.user
    site = request.session.get('site')

    site_text_dict = {'nbn':'c5', 'duck':'rect.jpg'}
    site_text = site_text_dict[site]

    user_imgs = [uu.image for uu in User_states_image.objects.all() if uu.user == user] #retrieve all images the user has labelled
    not_categorized = [im for im in Image.objects.all() if im not in user_imgs] #which ones are not in the list
    site_imgs = [im for im in not_categorized if site_text in im.filename]

    image = get_object_or_404(Image, pk = site_imgs[0].pk) #can choose to randomize or not, for not take each one

    return render(request, 'polls/display_image.html', {'image': image, 'states':State.objects.all(), 'site':site})


def vote(request):
    image_id = request.POST['image_pk']
    image = get_object_or_404(Image, pk = image_id)
    user = request.user

    state = request.POST.get('state')

    selected_choice = State.objects.get(pk = state)

    if len(User_states_image.objects.filter(image=image, user=user)) >= 1:
        uu = User_states_image.objects.get(image=image, user=user)
        uu.delete()

    User_states_image.objects.create(state = selected_choice, image = image, user = user)

    return HttpResponseRedirect(reverse('polls:display_image'))


def select_site(request):
    site = request.POST['site']
    request.session['site'] = site
    return redirect('polls:display_image')

def site_selection(request):
    #can i do this without having a view??
    return render(request, 'polls/site_selection.html')

users/views.py
from django.shortcuts import render
from django.contrib.auth.forms import UserCreationForm

def register(request):
    form = UserCreationForm()
    return render(request, 'users/register.html', {'form':form})



# Create your views here.

polls/templates/polls/display_image.html
{% extends "polls/header.html" %}
{% block content %}
{% load static %}
<body>
<nav>
    <div class="nav-wrapper">
        <ul class="left hide-on-med-and-down">
            <li> Logged in as {{ user.username }}</li>
        </ul>
        <ul class="right hide-on-med-and-down">
            <li> <a href={% url 'polls:site_selection' %}>Select Site</a></li>
            <li> <a href={% url 'polls:logout' %}>Logout</a></li>
        </ul>
    </div>
</nav>

<h3>Classify this image for {{ site }} </h3>

<img src = {% static image.filename %}>

<ul>
  <form action="{% url 'polls:vote' %}" method="post"> {% csrf_token %}
    <input type="hidden" name="image_pk" value="{{ image.pk }}">
        {% for state in states %}
            <p>
            <label>
            <input type="radio" name="state" id="state{{ forloop.counter }}" value="{{ state.pk }}" />
                <span style="color:black"> {{ state.name }} </span>
            </label>
{#    <input type="checkbox" name="state" id="state{{ forloop.counter }}" value="{{ state.pk }}"> is site{{ forloop }} access the site object within the for loop? #}
{#    <label for="state{{ forloop.counter }}">{{ state.name }}</label><br>#}
        {% endfor %}
    <p>
    <input type="submit" value="Vote">
  </form>
    <input type=button value="Previous Page" onClick="javascript:history.go(-1);">


{% endblock %}

polls/templates/polls/header.html
<head>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</head>
<body>
    <div class="container">
    <br>
        {% block content %}
        {% endblock %}
    </div>
</body>

polls/templates/polls/login.html
{% extends "polls/header.html" %}
{% block content %}
    {% if messages %}
        {% for message in messages %}
            <script>M.toast({html: "{{message}}", classes: 'blue rounded', displayLength:5000})</script>
        {% endfor %}
    {% endif %}
    <h2> Thanks for being willing to classify a few images! </h2>


        <form method="POST">
        {% csrf_token %}
        {{form.as_p}}
            <button style="background-color:#F4EB16; color:blue" class="btn btn-outline-info" type="submit">Login</button>
        </form>
        Don't have an account? <a href={% url 'polls:register' %}><strong>Register here</strong></a>!
{% endblock %}

polls/templates/polls/register.html
{% extends "polls/header.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                {{ form.as_p }}
            </fieldset>
            <div class="form-group">
                <button type="submit" class="btn">Register</button>
            </div>
        </form>

{% endblock content %}

polls/templates/polls/site_selection.html
{% extends "polls/header.html" %}
{% block content %}
    {% if messages %}
        {% for message in messages %}
            <script>M.toast({html: "{{message}}", classes: 'blue rounded', displayLength:5000})</script>
        {% endfor %}
    {% endif %}
    <h3> Select a site which you wish to classify: </h3>
    <form action="{% url 'polls:select_site' %}" method="post">
        {% csrf_token %}
        <button class="waves-effect waves-light btn-large" type="submit" name="site" id='nbn' value="nbn">Narrabeen</button>
        <button class="waves-effect waves-light btn-large" type="submit" name="site" id='duck' value="duck">Duck</button>
    </form>
{% endblock %}